/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 scene.gltf
Author: MADE.COM (https://sketchfab.com/made-it)
License: CC-BY-NC-4.0 (http://creativecommons.org/licenses/by-nc/4.0/)
Source: https://sketchfab.com/3d-models/margot-2-seater-sofa-old-rose-velvet-b3d693a003c94f4e989c08fe08c3af8c
Title: Margot 2 Seater Sofa, Old Rose Velvet
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scene.gltf')
  return (
    <group {...props} dispose={null}>
      <group position={[0, 0.42, -30]} rotation={[-Math.PI / 2, 0, 0]}>
        <group position={[-27.52, 0, -30]}>
          <mesh geometry={nodes.Margot_2_Seater_Sofa__Velvet_0.geometry} material={materials.Wood} />
          <mesh geometry={nodes.Margot_2_Seater_Sofa_Gold_0.geometry} material={materials.Gold} />
          <mesh geometry={nodes.Margot_2_Seater_Sofa_Wood_0.geometry} material={materials.Velvet} />
        </group>
      </group>
      {/* <mesh geometry={nodes.Plane001_FLOOR_0.geometry} material={materials.FLOOR} rotation={[-Math.PI / 2, 0, 0]} /> */}
    </group>
  )
}

useGLTF.preload('/scene.gltf')
